### ISSUE TITLE
Not clear how to solder jack for midi

### ISSUE THREAD

**Issue by 60pfennig** [SoundCodes/8knobs#1]
Hello :)
It is not clear for me which pin at the 3.5mm jack is for the tip and which is for the ring. Does it matter?
Greets Felix

**Comment by SubstanceD** [comment]
Hey @60pfennig polarity of the 3.5mm stereo connector does matter. 
On the back side of the connector it has tiny number printed. 1= tip, 2=ring
Also the below image may make it more clear.
https://github.com/SoundCodes/8knobs/blob/master/DIY%20Instructions/3.5mm.jpg

**Comment by 60pfennig** [comment]
Thanks for the clarification :)
